# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drill_box_every_pole_distance.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1575, 870)
        font = QtGui.QFont()
        font.setPointSize(18)
        Form.setFont(font)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(210, 70, 80, 32))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(590, 70, 80, 32))
        self.pushButton_12.setCheckable(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(920, 70, 80, 32))
        self.pushButton_13.setCheckable(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(560, 120, 211, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 7, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 6, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 5, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 3, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 5, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 6, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 7, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 8, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 2, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 1, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 4, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 8, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_22.setCheckable(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 3, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_2.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 4, 1, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_23.setCheckable(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 9, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_2.addWidget(self.lineEdit_20, 9, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(900, 110, 211, 541))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_24.setCheckable(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 2, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 7, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 6, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_26.setCheckable(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 5, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_3.addWidget(self.lineEdit_22, 3, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_3.addWidget(self.lineEdit_23, 5, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_3.addWidget(self.lineEdit_24, 6, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_27.setCheckable(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_3.addWidget(self.pushButton_27, 7, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_3.addWidget(self.lineEdit_25, 8, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_3.addWidget(self.lineEdit_26, 2, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_28.setCheckable(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_3.addWidget(self.pushButton_28, 0, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_29.setCheckable(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_3.addWidget(self.pushButton_29, 1, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_30.setCheckable(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 4, 0, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_31.setCheckable(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_3.addWidget(self.pushButton_31, 8, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_32.setCheckable(True)
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_3.addWidget(self.pushButton_32, 3, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_3.addWidget(self.lineEdit_27, 0, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_3.addWidget(self.lineEdit_28, 4, 1, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_3.addWidget(self.lineEdit_29, 1, 1, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_33.setCheckable(True)
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_3.addWidget(self.pushButton_33, 9, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_3.addWidget(self.lineEdit_30, 9, 1, 1, 1)
        self.pushButton_114 = QtWidgets.QPushButton(Form)
        self.pushButton_114.setGeometry(QtCore.QRect(330, 700, 201, 41))
        self.pushButton_114.setCheckable(True)
        self.pushButton_114.setObjectName("pushButton_114")
        self.pushButton_115 = QtWidgets.QPushButton(Form)
        self.pushButton_115.setGeometry(QtCore.QRect(620, 700, 201, 41))
        self.pushButton_115.setObjectName("pushButton_115")
        self.pushButton_116 = QtWidgets.QPushButton(Form)
        self.pushButton_116.setGeometry(QtCore.QRect(840, 700, 201, 41))
        self.pushButton_116.setObjectName("pushButton_116")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 130, 217, 541))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 5, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 8, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 8, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 5, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 9, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 7, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 6, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 7, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 9, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 70, 101, 51))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(700, 60, 101, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 20, 61, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(340, 20, 101, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(600, 20, 61, 51))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(710, 10, 101, 51))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(930, 10, 61, 51))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1020, 10, 101, 51))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(1030, 60, 101, 51))
        self.label_11.setObjectName("label_11")
        self.pushButton_121 = QtWidgets.QPushButton(Form)
        self.pushButton_121.setGeometry(QtCore.QRect(20, 700, 201, 41))
        self.pushButton_121.setCheckable(True)
        self.pushButton_121.setObjectName("pushButton_121")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(422, 625, 35, 28))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(422, 572, 35, 28))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(422, 519, 35, 28))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(422, 466, 35, 28))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Form)
        self.radioButton_5.setGeometry(QtCore.QRect(422, 413, 35, 28))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setGeometry(QtCore.QRect(422, 360, 35, 28))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(Form)
        self.radioButton_7.setGeometry(QtCore.QRect(422, 307, 35, 28))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setGeometry(QtCore.QRect(422, 254, 35, 28))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(Form)
        self.radioButton_9.setGeometry(QtCore.QRect(422, 201, 35, 28))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(Form)
        self.radioButton_10.setGeometry(QtCore.QRect(422, 148, 47, 28))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(Form)
        self.radioButton_11.setGeometry(QtCore.QRect(781, 617, 47, 28))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(Form)
        self.radioButton_12.setGeometry(QtCore.QRect(781, 564, 47, 28))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(Form)
        self.radioButton_13.setGeometry(QtCore.QRect(781, 511, 47, 28))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(Form)
        self.radioButton_14.setGeometry(QtCore.QRect(781, 458, 47, 28))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(Form)
        self.radioButton_15.setGeometry(QtCore.QRect(781, 405, 47, 28))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(Form)
        self.radioButton_16.setGeometry(QtCore.QRect(781, 352, 47, 28))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(Form)
        self.radioButton_17.setGeometry(QtCore.QRect(781, 299, 47, 28))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(Form)
        self.radioButton_18.setGeometry(QtCore.QRect(781, 246, 47, 28))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(Form)
        self.radioButton_19.setGeometry(QtCore.QRect(781, 193, 47, 28))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(Form)
        self.radioButton_20.setGeometry(QtCore.QRect(781, 140, 47, 28))
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_21 = QtWidgets.QRadioButton(Form)
        self.radioButton_21.setGeometry(QtCore.QRect(1121, 607, 47, 28))
        self.radioButton_21.setObjectName("radioButton_21")
        self.radioButton_22 = QtWidgets.QRadioButton(Form)
        self.radioButton_22.setGeometry(QtCore.QRect(1121, 554, 47, 28))
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(Form)
        self.radioButton_23.setGeometry(QtCore.QRect(1121, 501, 47, 28))
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(Form)
        self.radioButton_24.setGeometry(QtCore.QRect(1121, 448, 47, 28))
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_25 = QtWidgets.QRadioButton(Form)
        self.radioButton_25.setGeometry(QtCore.QRect(1121, 395, 47, 28))
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(Form)
        self.radioButton_26.setGeometry(QtCore.QRect(1121, 342, 47, 28))
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(Form)
        self.radioButton_27.setGeometry(QtCore.QRect(1121, 289, 47, 28))
        self.radioButton_27.setObjectName("radioButton_27")
        self.radioButton_28 = QtWidgets.QRadioButton(Form)
        self.radioButton_28.setGeometry(QtCore.QRect(1121, 236, 47, 28))
        self.radioButton_28.setObjectName("radioButton_28")
        self.radioButton_29 = QtWidgets.QRadioButton(Form)
        self.radioButton_29.setGeometry(QtCore.QRect(1121, 183, 47, 28))
        self.radioButton_29.setObjectName("radioButton_29")
        self.radioButton_30 = QtWidgets.QRadioButton(Form)
        self.radioButton_30.setGeometry(QtCore.QRect(1121, 130, 47, 28))
        self.radioButton_30.setObjectName("radioButton_30")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(1220, 150, 361, 631))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setGeometry(QtCore.QRect(110, 20, 171, 31))
        self.label_12.setObjectName("label_12")
        self.verticalSlider = QtWidgets.QSlider(self.page_3)
        self.verticalSlider.setGeometry(QtCore.QRect(140, 110, 91, 431))
        self.verticalSlider.setMaximum(1000)
        self.verticalSlider.setProperty("value", 400)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.pushButton_43 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_43.setGeometry(QtCore.QRect(110, 560, 191, 31))
        self.pushButton_43.setObjectName("pushButton_43")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_118 = QtWidgets.QPushButton(self.page)
        self.pushButton_118.setGeometry(QtCore.QRect(0, 20, 281, 41))
        self.pushButton_118.setObjectName("pushButton_118")
        self.horizontalSlider = QtWidgets.QSlider(self.page)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 90, 221, 20))
        self.horizontalSlider.setMaximum(80)
        self.horizontalSlider.setProperty("value", 8)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(100, 120, 181, 41))
        self.label.setObjectName("label")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(70, 270, 251, 19))
        self.horizontalSlider_2.setMaximum(30)
        self.horizontalSlider_2.setProperty("value", 5)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.pushButton_119 = QtWidgets.QPushButton(self.page)
        self.pushButton_119.setGeometry(QtCore.QRect(60, 210, 261, 41))
        self.pushButton_119.setObjectName("pushButton_119")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(130, 300, 181, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton_120 = QtWidgets.QPushButton(self.page)
        self.pushButton_120.setGeometry(QtCore.QRect(40, 370, 291, 41))
        self.pushButton_120.setObjectName("pushButton_120")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(130, 460, 181, 41))
        self.label_13.setObjectName("label_13")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.page)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(60, 430, 251, 19))
        self.horizontalSlider_3.setMaximum(30)
        self.horizontalSlider_3.setProperty("value", 5)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.pushButton_117 = QtWidgets.QPushButton(self.page)
        self.pushButton_117.setGeometry(QtCore.QRect(40, 520, 281, 41))
        self.pushButton_117.setObjectName("pushButton_117")
        self.lineEdit_138 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_138.setGeometry(QtCore.QRect(180, 580, 141, 41))
        self.lineEdit_138.setObjectName("lineEdit_138")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_32.setGeometry(QtCore.QRect(180, 70, 121, 31))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_31.setGeometry(QtCore.QRect(30, 70, 121, 31))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(30, 20, 101, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(180, 20, 101, 31))
        self.label_16.setObjectName("label_16")
        self.pushButton_34 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_34.setGeometry(QtCore.QRect(0, 180, 231, 41))
        self.pushButton_34.setObjectName("pushButton_34")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_33.setGeometry(QtCore.QRect(120, 140, 121, 31))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_38.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_37.setGeometry(QtCore.QRect(0, 140, 121, 31))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_34.setGeometry(QtCore.QRect(240, 190, 121, 31))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_35.setGeometry(QtCore.QRect(10, 350, 211, 41))
        self.pushButton_35.setObjectName("pushButton_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_36.setGeometry(QtCore.QRect(10, 300, 111, 31))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_35.setGeometry(QtCore.QRect(130, 300, 101, 31))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_40.setGeometry(QtCore.QRect(240, 350, 121, 31))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_39.setGeometry(QtCore.QRect(240, 300, 121, 31))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.pushButton_39 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_39.setGeometry(QtCore.QRect(50, 520, 211, 41))
        self.pushButton_39.setCheckable(True)
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_40.setGeometry(QtCore.QRect(50, 470, 211, 41))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_41.setGeometry(QtCore.QRect(30, 230, 271, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_42.setGeometry(QtCore.QRect(40, 400, 271, 41))
        self.pushButton_42.setObjectName("pushButton_42")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton_36 = QtWidgets.QPushButton(Form)
        self.pushButton_36.setGeometry(QtCore.QRect(1200, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setCheckable(True)
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(Form)
        self.pushButton_37.setGeometry(QtCore.QRect(1360, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setCheckable(True)
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(Form)
        self.pushButton_38.setGeometry(QtCore.QRect(1280, 790, 181, 41))
        self.pushButton_38.setCheckable(False)
        self.pushButton_38.setAutoExclusive(False)
        self.pushButton_38.setObjectName("pushButton_38")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_11.setText(_translate("Form", "内栏"))
        self.pushButton_12.setText(_translate("Form", "中栏"))
        self.pushButton_13.setText(_translate("Form", "外栏"))
        self.pushButton_14.setText(_translate("Form", "中栏8"))
        self.pushButton_15.setText(_translate("Form", "中栏4"))
        self.pushButton_16.setText(_translate("Form", "中栏5"))
        self.pushButton_17.setText(_translate("Form", "中栏3"))
        self.pushButton_18.setText(_translate("Form", "中栏10"))
        self.pushButton_19.setText(_translate("Form", "中栏9"))
        self.pushButton_20.setText(_translate("Form", "中栏6"))
        self.pushButton_21.setText(_translate("Form", "中栏2"))
        self.pushButton_22.setText(_translate("Form", "中栏7"))
        self.pushButton_23.setText(_translate("Form", "中栏1"))
        self.pushButton_24.setText(_translate("Form", "外栏8"))
        self.pushButton_25.setText(_translate("Form", "外栏4"))
        self.pushButton_26.setText(_translate("Form", "外栏5"))
        self.pushButton_27.setText(_translate("Form", "外栏3"))
        self.pushButton_28.setText(_translate("Form", "外栏10"))
        self.pushButton_29.setText(_translate("Form", "外栏9"))
        self.pushButton_30.setText(_translate("Form", "外栏6"))
        self.pushButton_31.setText(_translate("Form", "外栏2"))
        self.pushButton_32.setText(_translate("Form", "外栏7"))
        self.pushButton_33.setText(_translate("Form", "外栏1"))
        self.pushButton_114.setText(_translate("Form", "全部设置已经锁定"))
        self.pushButton_115.setText(_translate("Form", "读取旧数据"))
        self.pushButton_116.setText(_translate("Form", "数据保存"))
        self.pushButton_6.setText(_translate("Form", "内栏5"))
        self.pushButton_9.setText(_translate("Form", "内栏2"))
        self.pushButton.setText(_translate("Form", "内栏10"))
        self.pushButton_10.setText(_translate("Form", "内栏1"))
        self.pushButton_4.setText(_translate("Form", "内栏7"))
        self.pushButton_7.setText(_translate("Form", "内栏4"))
        self.pushButton_2.setText(_translate("Form", "内栏9"))
        self.pushButton_3.setText(_translate("Form", "内栏8"))
        self.pushButton_8.setText(_translate("Form", "内栏3"))
        self.pushButton_5.setText(_translate("Form", "内栏6"))
        self.label_3.setText(_translate("Form", "当前位置"))
        self.label_4.setText(_translate("Form", "当前位置"))
        self.label_5.setText(_translate("Form", "坐标"))
        self.label_6.setText(_translate("Form", "内栏坐标"))
        self.label_7.setText(_translate("Form", "坐标"))
        self.label_8.setText(_translate("Form", "中栏坐标"))
        self.label_9.setText(_translate("Form", "坐标"))
        self.label_10.setText(_translate("Form", "外栏坐标"))
        self.label_11.setText(_translate("Form", "当前位置"))
        self.pushButton_121.setText(_translate("Form", "测试开始"))
        self.radioButton.setText(_translate("Form", "1"))
        self.radioButton_2.setText(_translate("Form", "2"))
        self.radioButton_3.setText(_translate("Form", "3"))
        self.radioButton_4.setText(_translate("Form", "4"))
        self.radioButton_5.setText(_translate("Form", "5"))
        self.radioButton_6.setText(_translate("Form", "6"))
        self.radioButton_7.setText(_translate("Form", "7"))
        self.radioButton_8.setText(_translate("Form", "8"))
        self.radioButton_9.setText(_translate("Form", "9"))
        self.radioButton_10.setText(_translate("Form", "10"))
        self.radioButton_11.setText(_translate("Form", "11"))
        self.radioButton_12.setText(_translate("Form", "12"))
        self.radioButton_13.setText(_translate("Form", "13"))
        self.radioButton_14.setText(_translate("Form", "14"))
        self.radioButton_15.setText(_translate("Form", "15"))
        self.radioButton_16.setText(_translate("Form", "16"))
        self.radioButton_17.setText(_translate("Form", "17"))
        self.radioButton_18.setText(_translate("Form", "18"))
        self.radioButton_19.setText(_translate("Form", "19"))
        self.radioButton_20.setText(_translate("Form", "20"))
        self.radioButton_21.setText(_translate("Form", "21"))
        self.radioButton_22.setText(_translate("Form", "22"))
        self.radioButton_23.setText(_translate("Form", "23"))
        self.radioButton_24.setText(_translate("Form", "24"))
        self.radioButton_25.setText(_translate("Form", "25"))
        self.radioButton_26.setText(_translate("Form", "26"))
        self.radioButton_27.setText(_translate("Form", "27"))
        self.radioButton_28.setText(_translate("Form", "28"))
        self.radioButton_29.setText(_translate("Form", "29"))
        self.radioButton_30.setText(_translate("Form", "30"))
        self.label_12.setText(_translate("Form", "开始坐标设置"))
        self.pushButton_43.setText(_translate("Form", "距离"))
        self.pushButton_118.setText(_translate("Form", "抓手位移误差设置"))
        self.label.setText(_translate("Form", "      8 毫米"))
        self.pushButton_119.setText(_translate("Form", "钻箱上下误差设置"))
        self.label_2.setText(_translate("Form", "      5 毫米"))
        self.pushButton_120.setText(_translate("Form", "抓手速度伸缩范围设置"))
        self.label_13.setText(_translate("Form", "      5 毫米"))
        self.pushButton_117.setText(_translate("Form", "取钻杆位移允许误差"))
        self.lineEdit_138.setText(_translate("Form", "10"))
        self.lineEdit_32.setText(_translate("Form", "300"))
        self.lineEdit_31.setText(_translate("Form", "700"))
        self.lineEdit_31.setPlaceholderText(_translate("Form", "起点坐标"))
        self.label_15.setText(_translate("Form", "起点坐标"))
        self.label_16.setText(_translate("Form", "指定距离"))
        self.pushButton_34.setText(_translate("Form", "指定距离速度测试"))
        self.lineEdit_33.setPlaceholderText(_translate("Form", "测试结果"))
        self.lineEdit_38.setText(_translate("Form", "标准距离"))
        self.lineEdit_38.setPlaceholderText(_translate("Form", "标准结果"))
        self.lineEdit_37.setText(_translate("Form", "实际距离"))
        self.lineEdit_34.setPlaceholderText(_translate("Form", "标准结果"))
        self.pushButton_35.setText(_translate("Form", "带负重测试"))
        self.lineEdit_36.setText(_translate("Form", "实际距离"))
        self.lineEdit_36.setPlaceholderText(_translate("Form", "标准结果"))
        self.lineEdit_35.setText(_translate("Form", "测试结果"))
        self.lineEdit_35.setPlaceholderText(_translate("Form", "标准结果"))
        self.lineEdit_40.setPlaceholderText(_translate("Form", "标准结果"))
        self.lineEdit_39.setText(_translate("Form", "标准距离"))
        self.lineEdit_39.setPlaceholderText(_translate("Form", "标准结果"))
        self.pushButton_39.setText(_translate("Form", "测试锁定"))
        self.pushButton_40.setText(_translate("Form", "测试数据保存"))
        self.pushButton_41.setText(_translate("Form", "保存为标准值"))
        self.pushButton_42.setText(_translate("Form", "保存为标准值"))
        self.pushButton_36.setText(_translate("Form", "位移误差设置"))
        self.pushButton_37.setText(_translate("Form", "抓手速度测试"))
        self.pushButton_38.setText(_translate("Form", "起点坐标选择"))
