# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guide_start_to_pole.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1905, 885)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        Form.setFont(font)
        self.layoutWidget_34 = QtWidgets.QWidget(Form)
        self.layoutWidget_34.setGeometry(QtCore.QRect(340, 10, 1331, 441))
        self.layoutWidget_34.setObjectName("layoutWidget_34")
        self.gridLayout_75 = QtWidgets.QGridLayout(self.layoutWidget_34)
        self.gridLayout_75.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_75.setObjectName("gridLayout_75")
        self.lineEdit_783 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_783.setObjectName("lineEdit_783")
        self.gridLayout_75.addWidget(self.lineEdit_783, 2, 4, 1, 1)
        self.label_1315 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1315.sizePolicy().hasHeightForWidth())
        self.label_1315.setSizePolicy(sizePolicy)
        self.label_1315.setObjectName("label_1315")
        self.gridLayout_75.addWidget(self.label_1315, 5, 0, 1, 1)
        self.lineEdit_803 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_803.setObjectName("lineEdit_803")
        self.gridLayout_75.addWidget(self.lineEdit_803, 6, 5, 1, 1)
        self.lineEdit_802 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_802.setObjectName("lineEdit_802")
        self.gridLayout_75.addWidget(self.lineEdit_802, 5, 5, 1, 1)
        self.lineEdit_798 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_798.setObjectName("lineEdit_798")
        self.gridLayout_75.addWidget(self.lineEdit_798, 1, 5, 1, 1)
        self.label_1312 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1312.sizePolicy().hasHeightForWidth())
        self.label_1312.setSizePolicy(sizePolicy)
        self.label_1312.setObjectName("label_1312")
        self.gridLayout_75.addWidget(self.label_1312, 2, 0, 1, 1)
        self.label_1318 = QtWidgets.QLabel(self.layoutWidget_34)
        self.label_1318.setObjectName("label_1318")
        self.gridLayout_75.addWidget(self.label_1318, 0, 2, 1, 1)
        self.lineEdit_788 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_788.setObjectName("lineEdit_788")
        self.gridLayout_75.addWidget(self.lineEdit_788, 5, 4, 1, 1)
        self.lineEdit_794 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_794.setObjectName("lineEdit_794")
        self.gridLayout_75.addWidget(self.lineEdit_794, 3, 2, 1, 1)
        self.lineEdit_796 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_796.setObjectName("lineEdit_796")
        self.gridLayout_75.addWidget(self.lineEdit_796, 5, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_75.addWidget(self.lineEdit_9, 7, 3, 1, 1)
        self.label_1310 = QtWidgets.QLabel(self.layoutWidget_34)
        self.label_1310.setObjectName("label_1310")
        self.gridLayout_75.addWidget(self.label_1310, 0, 4, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_75.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.lineEdit_782 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_782.setObjectName("lineEdit_782")
        self.gridLayout_75.addWidget(self.lineEdit_782, 2, 3, 1, 1)
        self.lineEdit_785 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_785.setObjectName("lineEdit_785")
        self.gridLayout_75.addWidget(self.lineEdit_785, 3, 4, 1, 1)
        self.label_1319 = QtWidgets.QLabel(self.layoutWidget_34)
        self.label_1319.setObjectName("label_1319")
        self.gridLayout_75.addWidget(self.label_1319, 0, 5, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_75.addWidget(self.lineEdit_13, 8, 2, 1, 1)
        self.label_1313 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1313.sizePolicy().hasHeightForWidth())
        self.label_1313.setSizePolicy(sizePolicy)
        self.label_1313.setObjectName("label_1313")
        self.gridLayout_75.addWidget(self.label_1313, 3, 0, 1, 1)
        self.label_1314 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1314.sizePolicy().hasHeightForWidth())
        self.label_1314.setSizePolicy(sizePolicy)
        self.label_1314.setObjectName("label_1314")
        self.gridLayout_75.addWidget(self.label_1314, 4, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_75.addWidget(self.lineEdit_14, 8, 3, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_75.addWidget(self.lineEdit_10, 7, 4, 1, 1)
        self.lineEdit_790 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_790.setObjectName("lineEdit_790")
        self.gridLayout_75.addWidget(self.lineEdit_790, 6, 4, 1, 1)
        self.label_1316 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1316.sizePolicy().hasHeightForWidth())
        self.label_1316.setSizePolicy(sizePolicy)
        self.label_1316.setObjectName("label_1316")
        self.gridLayout_75.addWidget(self.label_1316, 6, 0, 1, 1)
        self.lineEdit_801 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_801.setObjectName("lineEdit_801")
        self.gridLayout_75.addWidget(self.lineEdit_801, 4, 5, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_75.addWidget(self.lineEdit_16, 8, 5, 1, 1)
        self.lineEdit_799 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_799.setObjectName("lineEdit_799")
        self.gridLayout_75.addWidget(self.lineEdit_799, 2, 5, 1, 1)
        self.label_1309 = QtWidgets.QLabel(self.layoutWidget_34)
        self.label_1309.setObjectName("label_1309")
        self.gridLayout_75.addWidget(self.label_1309, 0, 3, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_75.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.lineEdit_784 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_784.setObjectName("lineEdit_784")
        self.gridLayout_75.addWidget(self.lineEdit_784, 3, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_75.addWidget(self.lineEdit_6, 6, 1, 1, 1)
        self.lineEdit_791 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_791.setObjectName("lineEdit_791")
        self.gridLayout_75.addWidget(self.lineEdit_791, 6, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_75.addWidget(self.lineEdit_7, 7, 1, 1, 1)
        self.lineEdit_793 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_793.setObjectName("lineEdit_793")
        self.gridLayout_75.addWidget(self.lineEdit_793, 2, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_75.addWidget(self.lineEdit_11, 7, 5, 1, 1)
        self.label_1311 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1311.sizePolicy().hasHeightForWidth())
        self.label_1311.setSizePolicy(sizePolicy)
        self.label_1311.setObjectName("label_1311")
        self.gridLayout_75.addWidget(self.label_1311, 1, 0, 1, 1)
        self.lineEdit_786 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_786.setObjectName("lineEdit_786")
        self.gridLayout_75.addWidget(self.lineEdit_786, 4, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_75.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_75.addWidget(self.lineEdit_12, 8, 1, 1, 1)
        self.lineEdit_787 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_787.setObjectName("lineEdit_787")
        self.gridLayout_75.addWidget(self.lineEdit_787, 4, 3, 1, 1)
        self.lineEdit_797 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_797.setObjectName("lineEdit_797")
        self.gridLayout_75.addWidget(self.lineEdit_797, 6, 2, 1, 1)
        self.lineEdit_795 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_795.setObjectName("lineEdit_795")
        self.gridLayout_75.addWidget(self.lineEdit_795, 4, 2, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_75.addWidget(self.lineEdit_15, 8, 4, 1, 1)
        self.label_1320 = QtWidgets.QLabel(self.layoutWidget_34)
        self.label_1320.setObjectName("label_1320")
        self.gridLayout_75.addWidget(self.label_1320, 0, 1, 1, 1)
        self.lineEdit_781 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_781.setObjectName("lineEdit_781")
        self.gridLayout_75.addWidget(self.lineEdit_781, 1, 4, 1, 1)
        self.label_1317 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1317.sizePolicy().hasHeightForWidth())
        self.label_1317.setSizePolicy(sizePolicy)
        self.label_1317.setIndent(1)
        self.label_1317.setObjectName("label_1317")
        self.gridLayout_75.addWidget(self.label_1317, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_75.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_75.addWidget(self.lineEdit_8, 7, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_75.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_789 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_789.setObjectName("lineEdit_789")
        self.gridLayout_75.addWidget(self.lineEdit_789, 5, 3, 1, 1)
        self.lineEdit_792 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_792.setObjectName("lineEdit_792")
        self.gridLayout_75.addWidget(self.lineEdit_792, 1, 2, 1, 1)
        self.lineEdit_780 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_780.setObjectName("lineEdit_780")
        self.gridLayout_75.addWidget(self.lineEdit_780, 1, 3, 1, 1)
        self.lineEdit_800 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_800.setObjectName("lineEdit_800")
        self.gridLayout_75.addWidget(self.lineEdit_800, 3, 5, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_75.addWidget(self.lineEdit_17, 9, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_75.addWidget(self.lineEdit_18, 9, 2, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_75.addWidget(self.lineEdit_19, 9, 3, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_75.addWidget(self.lineEdit_20, 9, 4, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_34)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_75.addWidget(self.lineEdit_21, 9, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_75.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_75.addWidget(self.label_5, 8, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_75.addWidget(self.label_6, 9, 0, 1, 1)
        self.gridLayout_75.setRowMinimumHeight(0, 1)
        self.gridLayout_75.setRowMinimumHeight(1, 1)
        self.gridLayout_75.setRowMinimumHeight(2, 1)
        self.gridLayout_75.setRowMinimumHeight(3, 1)
        self.gridLayout_75.setRowMinimumHeight(4, 1)
        self.gridLayout_75.setRowMinimumHeight(5, 1)
        self.gridLayout_75.setRowMinimumHeight(6, 1)
        self.gridLayout_75.setRowMinimumHeight(7, 1)
        self.gridLayout_75.setRowMinimumHeight(8, 1)
        self.gridLayout_75.setRowMinimumHeight(9, 1)
        self.gridLayout_75.setColumnStretch(0, 1)
        self.gridLayout_75.setColumnStretch(1, 1)
        self.gridLayout_75.setColumnStretch(2, 1)
        self.gridLayout_75.setColumnStretch(3, 1)
        self.gridLayout_75.setColumnStretch(4, 1)
        self.gridLayout_75.setColumnStretch(5, 1)
        self.gridLayout_75.setRowStretch(0, 1)
        self.gridLayout_75.setRowStretch(1, 1)
        self.gridLayout_75.setRowStretch(2, 1)
        self.gridLayout_75.setRowStretch(3, 1)
        self.gridLayout_75.setRowStretch(4, 1)
        self.gridLayout_75.setRowStretch(5, 1)
        self.gridLayout_75.setRowStretch(6, 1)
        self.gridLayout_75.setRowStretch(7, 1)
        self.gridLayout_75.setRowStretch(8, 1)
        self.gridLayout_75.setRowStretch(9, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(740, 560, 161, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 560, 111, 31))
        self.label_3.setObjectName("label_3")
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setGeometry(QtCore.QRect(380, 610, 81, 160))
        self.verticalSlider.setMaximum(27)
        self.verticalSlider.setProperty("value", 17)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.verticalSlider_2 = QtWidgets.QSlider(Form)
        self.verticalSlider_2.setGeometry(QtCore.QRect(810, 630, 81, 160))
        self.verticalSlider_2.setMaximum(7)
        self.verticalSlider_2.setProperty("value", 4)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(180, 140, 141, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_2.addWidget(self.pushButton_13)
        self.verticalSlider_3 = QtWidgets.QSlider(Form)
        self.verticalSlider_3.setGeometry(QtCore.QRect(560, 610, 111, 160))
        self.verticalSlider_3.setMaximum(30)
        self.verticalSlider_3.setProperty("value", 12)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(540, 560, 111, 31))
        self.label_7.setObjectName("label_7")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(490, 500, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(350, 480, 121, 51))
        self.label_8.setObjectName("label_8")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(760, 500, 113, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(640, 480, 101, 51))
        self.label_2.setObjectName("label_2")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(1080, 670, 121, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(1010, 610, 113, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1020, 560, 111, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(1180, 560, 111, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        self.lineEdit_25.setGeometry(QtCore.QRect(1160, 610, 113, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 141, 561))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit_783.setText(_translate("Form", "20"))
        self.label_1315.setText(_translate("Form", "杆数5"))
        self.lineEdit_803.setText(_translate("Form", "195"))
        self.lineEdit_802.setText(_translate("Form", "195"))
        self.lineEdit_798.setText(_translate("Form", "90"))
        self.label_1312.setText(_translate("Form", "杆数2"))
        self.label_1318.setText(_translate("Form", "总度数"))
        self.lineEdit_788.setText(_translate("Form", "15"))
        self.lineEdit_794.setText(_translate("Form", "11"))
        self.lineEdit_796.setText(_translate("Form", "3"))
        self.label_1310.setText(_translate("Form", "本杆调整深度"))
        self.lineEdit_4.setText(_translate("Form", "35"))
        self.lineEdit_782.setText(_translate("Form", "4"))
        self.lineEdit_785.setText(_translate("Form", "20"))
        self.label_1319.setText(_translate("Form", "总深度"))
        self.label_1313.setText(_translate("Form", "杆数3"))
        self.label_1314.setText(_translate("Form", "杆数4"))
        self.lineEdit_790.setText(_translate("Form", "0"))
        self.label_1316.setText(_translate("Form", "杆数6"))
        self.lineEdit_801.setText(_translate("Form", "195"))
        self.lineEdit_799.setText(_translate("Form", "145"))
        self.label_1309.setText(_translate("Form", "本杆变化度数"))
        self.lineEdit_3.setText(_translate("Form", "55"))
        self.lineEdit_784.setText(_translate("Form", "4"))
        self.lineEdit_6.setText(_translate("Form", "0"))
        self.lineEdit_791.setText(_translate("Form", "0"))
        self.lineEdit_793.setText(_translate("Form", "15"))
        self.label_1311.setText(_translate("Form", "杆数1"))
        self.lineEdit_786.setText(_translate("Form", "20"))
        self.lineEdit.setText(_translate("Form", "95"))
        self.lineEdit_787.setText(_translate("Form", "4"))
        self.lineEdit_797.setText(_translate("Form", "0"))
        self.lineEdit_795.setText(_translate("Form", "7"))
        self.label_1320.setText(_translate("Form", "本杆增加深度"))
        self.lineEdit_781.setText(_translate("Form", "20"))
        self.label_1317.setText(_translate("Form", "杆号"))
        self.lineEdit_5.setText(_translate("Form", "15"))
        self.lineEdit_2.setText(_translate("Form", "75"))
        self.lineEdit_789.setText(_translate("Form", "0"))
        self.lineEdit_792.setText(_translate("Form", "19"))
        self.lineEdit_780.setText(_translate("Form", "4"))
        self.lineEdit_800.setText(_translate("Form", "180"))
        self.label_4.setText(_translate("Form", "杆数7"))
        self.label_5.setText(_translate("Form", "杆数8"))
        self.label_6.setText(_translate("Form", "杆数9"))
        self.label.setText(_translate("Form", "每杆计划变化度数"))
        self.label_3.setText(_translate("Form", "入坑总度数"))
        self.pushButton_8.setText(_translate("Form", "1号减"))
        self.pushButton_9.setText(_translate("Form", "2号减"))
        self.pushButton_10.setText(_translate("Form", "3号减"))
        self.pushButton_11.setText(_translate("Form", "4号减"))
        self.pushButton_12.setText(_translate("Form", "5号减"))
        self.pushButton_13.setText(_translate("Form", "6号减"))
        self.label_7.setText(_translate("Form", "入坑深度"))
        self.label_8.setText(_translate("Form", "深度合计"))
        self.lineEdit_23.setText(_translate("Form", "12"))
        self.label_2.setText(_translate("Form", "入坑深度"))
        self.pushButton_14.setText(_translate("Form", "自动计算"))
        self.label_9.setText(_translate("Form", "指定杆数"))
        self.label_10.setText(_translate("Form", "指定深度"))
        self.pushButton_2.setText(_translate("Form", "1号加"))
        self.pushButton_3.setText(_translate("Form", "2号加"))
        self.pushButton_4.setText(_translate("Form", "3号加"))
        self.pushButton_5.setText(_translate("Form", "4号加"))
        self.pushButton_6.setText(_translate("Form", "5号加"))
        self.pushButton_7.setText(_translate("Form", "6号加"))
