# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'out_hole_guide.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1752, 999)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.label_602 = QtWidgets.QLabel(Form)
        self.label_602.setGeometry(QtCore.QRect(350, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_602.setFont(font)
        self.label_602.setObjectName("label_602")
        self.pushButton_36 = QtWidgets.QPushButton(Form)
        self.pushButton_36.setGeometry(QtCore.QRect(1240, 130, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setCheckable(True)
        self.pushButton_36.setChecked(True)
        self.pushButton_36.setAutoExclusive(True)
        self.pushButton_36.setObjectName("pushButton_36")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(25, 360, 1251, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_665 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_665.sizePolicy().hasHeightForWidth())
        self.label_665.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_665.setFont(font)
        self.label_665.setObjectName("label_665")
        self.gridLayout_28.addWidget(self.label_665, 0, 0, 1, 1)
        self.label_680 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_680.sizePolicy().hasHeightForWidth())
        self.label_680.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_680.setFont(font)
        self.label_680.setObjectName("label_680")
        self.gridLayout_28.addWidget(self.label_680, 0, 5, 1, 1)
        self.lineEdit_375 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_375.sizePolicy().hasHeightForWidth())
        self.lineEdit_375.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_375.setFont(font)
        self.lineEdit_375.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_375.setObjectName("lineEdit_375")
        self.gridLayout_28.addWidget(self.lineEdit_375, 1, 5, 1, 1)
        self.lineEdit_376 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_376.sizePolicy().hasHeightForWidth())
        self.lineEdit_376.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_376.setFont(font)
        self.lineEdit_376.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_376.setObjectName("lineEdit_376")
        self.gridLayout_28.addWidget(self.lineEdit_376, 1, 4, 1, 1)
        self.label_664 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_664.sizePolicy().hasHeightForWidth())
        self.label_664.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_664.setFont(font)
        self.label_664.setObjectName("label_664")
        self.gridLayout_28.addWidget(self.label_664, 0, 6, 1, 1)
        self.lineEdit_359 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_359.sizePolicy().hasHeightForWidth())
        self.lineEdit_359.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_359.setFont(font)
        self.lineEdit_359.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_359.setObjectName("lineEdit_359")
        self.gridLayout_28.addWidget(self.lineEdit_359, 1, 7, 1, 1)
        self.label_682 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_682.sizePolicy().hasHeightForWidth())
        self.label_682.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_682.setFont(font)
        self.label_682.setObjectName("label_682")
        self.gridLayout_28.addWidget(self.label_682, 0, 3, 1, 1)
        self.lineEdit_362 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_362.sizePolicy().hasHeightForWidth())
        self.lineEdit_362.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_362.setFont(font)
        self.lineEdit_362.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_362.setObjectName("lineEdit_362")
        self.gridLayout_28.addWidget(self.lineEdit_362, 1, 8, 1, 1)
        self.lineEdit_360 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_360.sizePolicy().hasHeightForWidth())
        self.lineEdit_360.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_360.setFont(font)
        self.lineEdit_360.setMaxLength(2)
        self.lineEdit_360.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_360.setObjectName("lineEdit_360")
        self.gridLayout_28.addWidget(self.lineEdit_360, 1, 6, 1, 1)
        self.label_663 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_663.sizePolicy().hasHeightForWidth())
        self.label_663.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_663.setFont(font)
        self.label_663.setObjectName("label_663")
        self.gridLayout_28.addWidget(self.label_663, 0, 7, 1, 1)
        self.lineEdit_361 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_361.sizePolicy().hasHeightForWidth())
        self.lineEdit_361.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_361.setFont(font)
        self.lineEdit_361.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_361.setObjectName("lineEdit_361")
        self.gridLayout_28.addWidget(self.lineEdit_361, 1, 0, 1, 1)
        self.label_681 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_681.sizePolicy().hasHeightForWidth())
        self.label_681.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_681.setFont(font)
        self.label_681.setObjectName("label_681")
        self.gridLayout_28.addWidget(self.label_681, 0, 4, 1, 1)
        self.label_668 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_668.sizePolicy().hasHeightForWidth())
        self.label_668.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_668.setFont(font)
        self.label_668.setObjectName("label_668")
        self.gridLayout_28.addWidget(self.label_668, 0, 2, 1, 1)
        self.label_666 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_666.sizePolicy().hasHeightForWidth())
        self.label_666.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_666.setFont(font)
        self.label_666.setObjectName("label_666")
        self.gridLayout_28.addWidget(self.label_666, 0, 8, 1, 1)
        self.lineEdit_377 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_377.sizePolicy().hasHeightForWidth())
        self.lineEdit_377.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_377.setFont(font)
        self.lineEdit_377.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_377.setObjectName("lineEdit_377")
        self.gridLayout_28.addWidget(self.lineEdit_377, 1, 3, 1, 1)
        self.lineEdit_364 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_364.sizePolicy().hasHeightForWidth())
        self.lineEdit_364.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_364.setFont(font)
        self.lineEdit_364.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_364.setObjectName("lineEdit_364")
        self.gridLayout_28.addWidget(self.lineEdit_364, 1, 2, 1, 1)
        self.lineEdit_365 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_365.sizePolicy().hasHeightForWidth())
        self.lineEdit_365.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_365.setFont(font)
        self.lineEdit_365.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_365.setObjectName("lineEdit_365")
        self.gridLayout_28.addWidget(self.lineEdit_365, 1, 1, 1, 1)
        self.label_669 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_669.sizePolicy().hasHeightForWidth())
        self.label_669.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_669.setFont(font)
        self.label_669.setObjectName("label_669")
        self.gridLayout_28.addWidget(self.label_669, 0, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 110, 971, 221))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.lineEdit_453 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_453.sizePolicy().hasHeightForWidth())
        self.lineEdit_453.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_453.setFont(font)
        self.lineEdit_453.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_453.setObjectName("lineEdit_453")
        self.gridLayout_29.addWidget(self.lineEdit_453, 4, 4, 1, 1)
        self.lineEdit_434 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_434.sizePolicy().hasHeightForWidth())
        self.lineEdit_434.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_434.setFont(font)
        self.lineEdit_434.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_434.setObjectName("lineEdit_434")
        self.gridLayout_29.addWidget(self.lineEdit_434, 2, 2, 1, 1)
        self.lineEdit_371 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_371.sizePolicy().hasHeightForWidth())
        self.lineEdit_371.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_371.setFont(font)
        self.lineEdit_371.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_371.setObjectName("lineEdit_371")
        self.gridLayout_29.addWidget(self.lineEdit_371, 1, 4, 1, 1)
        self.label_674 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_674.sizePolicy().hasHeightForWidth())
        self.label_674.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_674.setFont(font)
        self.label_674.setObjectName("label_674")
        self.gridLayout_29.addWidget(self.label_674, 0, 5, 1, 1)
        self.label_673 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_673.sizePolicy().hasHeightForWidth())
        self.label_673.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_673.setFont(font)
        self.label_673.setObjectName("label_673")
        self.gridLayout_29.addWidget(self.label_673, 0, 1, 1, 1)
        self.lineEdit_445 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_445.sizePolicy().hasHeightForWidth())
        self.lineEdit_445.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_445.setFont(font)
        self.lineEdit_445.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_445.setObjectName("lineEdit_445")
        self.gridLayout_29.addWidget(self.lineEdit_445, 3, 4, 1, 1)
        self.lineEdit_452 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_452.sizePolicy().hasHeightForWidth())
        self.lineEdit_452.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_452.setFont(font)
        self.lineEdit_452.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_452.setObjectName("lineEdit_452")
        self.gridLayout_29.addWidget(self.lineEdit_452, 4, 3, 1, 1)
        self.lineEdit_441 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_441.sizePolicy().hasHeightForWidth())
        self.lineEdit_441.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_441.setFont(font)
        self.lineEdit_441.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_441.setObjectName("lineEdit_441")
        self.gridLayout_29.addWidget(self.lineEdit_441, 3, 0, 1, 1)
        self.label_672 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_672.sizePolicy().hasHeightForWidth())
        self.label_672.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_672.setFont(font)
        self.label_672.setObjectName("label_672")
        self.gridLayout_29.addWidget(self.label_672, 0, 0, 1, 1)
        self.lineEdit_436 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_436.sizePolicy().hasHeightForWidth())
        self.lineEdit_436.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_436.setFont(font)
        self.lineEdit_436.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_436.setObjectName("lineEdit_436")
        self.gridLayout_29.addWidget(self.lineEdit_436, 2, 4, 1, 1)
        self.lineEdit_449 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_449.sizePolicy().hasHeightForWidth())
        self.lineEdit_449.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_449.setFont(font)
        self.lineEdit_449.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_449.setObjectName("lineEdit_449")
        self.gridLayout_29.addWidget(self.lineEdit_449, 4, 0, 1, 1)
        self.lineEdit_454 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_454.sizePolicy().hasHeightForWidth())
        self.lineEdit_454.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_454.setFont(font)
        self.lineEdit_454.setText("")
        self.lineEdit_454.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_454.setObjectName("lineEdit_454")
        self.gridLayout_29.addWidget(self.lineEdit_454, 4, 5, 1, 1)
        self.lineEdit_448 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_448.sizePolicy().hasHeightForWidth())
        self.lineEdit_448.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_448.setFont(font)
        self.lineEdit_448.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_448.setObjectName("lineEdit_448")
        self.gridLayout_29.addWidget(self.lineEdit_448, 3, 7, 1, 1)
        self.label_677 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_677.sizePolicy().hasHeightForWidth())
        self.label_677.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_677.setFont(font)
        self.label_677.setObjectName("label_677")
        self.gridLayout_29.addWidget(self.label_677, 0, 6, 1, 1)
        self.lineEdit_372 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_372.sizePolicy().hasHeightForWidth())
        self.lineEdit_372.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_372.setFont(font)
        self.lineEdit_372.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_372.setObjectName("lineEdit_372")
        self.gridLayout_29.addWidget(self.lineEdit_372, 1, 5, 1, 1)
        self.label_679 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_679.sizePolicy().hasHeightForWidth())
        self.label_679.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_679.setFont(font)
        self.label_679.setObjectName("label_679")
        self.gridLayout_29.addWidget(self.label_679, 0, 7, 1, 1)
        self.lineEdit_368 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_368.sizePolicy().hasHeightForWidth())
        self.lineEdit_368.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_368.setFont(font)
        self.lineEdit_368.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_368.setObjectName("lineEdit_368")
        self.gridLayout_29.addWidget(self.lineEdit_368, 1, 1, 1, 1)
        self.lineEdit_444 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_444.sizePolicy().hasHeightForWidth())
        self.lineEdit_444.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_444.setFont(font)
        self.lineEdit_444.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_444.setObjectName("lineEdit_444")
        self.gridLayout_29.addWidget(self.lineEdit_444, 3, 3, 1, 1)
        self.lineEdit_450 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_450.sizePolicy().hasHeightForWidth())
        self.lineEdit_450.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_450.setFont(font)
        self.lineEdit_450.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_450.setObjectName("lineEdit_450")
        self.gridLayout_29.addWidget(self.lineEdit_450, 4, 1, 1, 1)
        self.lineEdit_451 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_451.sizePolicy().hasHeightForWidth())
        self.lineEdit_451.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_451.setFont(font)
        self.lineEdit_451.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_451.setObjectName("lineEdit_451")
        self.gridLayout_29.addWidget(self.lineEdit_451, 4, 2, 1, 1)
        self.lineEdit_374 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_374.sizePolicy().hasHeightForWidth())
        self.lineEdit_374.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_374.setFont(font)
        self.lineEdit_374.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_374.setObjectName("lineEdit_374")
        self.gridLayout_29.addWidget(self.lineEdit_374, 1, 7, 1, 1)
        self.lineEdit_447 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_447.sizePolicy().hasHeightForWidth())
        self.lineEdit_447.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_447.setFont(font)
        self.lineEdit_447.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_447.setObjectName("lineEdit_447")
        self.gridLayout_29.addWidget(self.lineEdit_447, 3, 6, 1, 1)
        self.lineEdit_433 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_433.sizePolicy().hasHeightForWidth())
        self.lineEdit_433.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_433.setFont(font)
        self.lineEdit_433.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_433.setObjectName("lineEdit_433")
        self.gridLayout_29.addWidget(self.lineEdit_433, 2, 1, 1, 1)
        self.lineEdit_469 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_469.sizePolicy().hasHeightForWidth())
        self.lineEdit_469.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_469.setFont(font)
        self.lineEdit_469.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_469.setObjectName("lineEdit_469")
        self.gridLayout_29.addWidget(self.lineEdit_469, 4, 7, 1, 1)
        self.label_671 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_671.sizePolicy().hasHeightForWidth())
        self.label_671.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_671.setFont(font)
        self.label_671.setObjectName("label_671")
        self.gridLayout_29.addWidget(self.label_671, 0, 2, 1, 1)
        self.lineEdit_369 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_369.sizePolicy().hasHeightForWidth())
        self.lineEdit_369.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_369.setFont(font)
        self.lineEdit_369.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_369.setObjectName("lineEdit_369")
        self.gridLayout_29.addWidget(self.lineEdit_369, 1, 2, 1, 1)
        self.lineEdit_442 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_442.sizePolicy().hasHeightForWidth())
        self.lineEdit_442.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_442.setFont(font)
        self.lineEdit_442.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_442.setObjectName("lineEdit_442")
        self.gridLayout_29.addWidget(self.lineEdit_442, 3, 1, 1, 1)
        self.lineEdit_446 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_446.sizePolicy().hasHeightForWidth())
        self.lineEdit_446.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_446.setFont(font)
        self.lineEdit_446.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_446.setObjectName("lineEdit_446")
        self.gridLayout_29.addWidget(self.lineEdit_446, 3, 5, 1, 1)
        self.lineEdit_439 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_439.sizePolicy().hasHeightForWidth())
        self.lineEdit_439.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_439.setFont(font)
        self.lineEdit_439.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_439.setObjectName("lineEdit_439")
        self.gridLayout_29.addWidget(self.lineEdit_439, 2, 7, 1, 1)
        self.lineEdit_438 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_438.sizePolicy().hasHeightForWidth())
        self.lineEdit_438.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_438.setFont(font)
        self.lineEdit_438.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_438.setObjectName("lineEdit_438")
        self.gridLayout_29.addWidget(self.lineEdit_438, 2, 6, 1, 1)
        self.label_675 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_675.sizePolicy().hasHeightForWidth())
        self.label_675.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_675.setFont(font)
        self.label_675.setObjectName("label_675")
        self.gridLayout_29.addWidget(self.label_675, 0, 3, 1, 1)
        self.lineEdit_435 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_435.sizePolicy().hasHeightForWidth())
        self.lineEdit_435.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_435.setFont(font)
        self.lineEdit_435.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_435.setObjectName("lineEdit_435")
        self.gridLayout_29.addWidget(self.lineEdit_435, 2, 3, 1, 1)
        self.lineEdit_468 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_468.sizePolicy().hasHeightForWidth())
        self.lineEdit_468.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_468.setFont(font)
        self.lineEdit_468.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_468.setObjectName("lineEdit_468")
        self.gridLayout_29.addWidget(self.lineEdit_468, 4, 6, 1, 1)
        self.lineEdit_443 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_443.sizePolicy().hasHeightForWidth())
        self.lineEdit_443.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_443.setFont(font)
        self.lineEdit_443.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_443.setObjectName("lineEdit_443")
        self.gridLayout_29.addWidget(self.lineEdit_443, 3, 2, 1, 1)
        self.label_676 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_676.sizePolicy().hasHeightForWidth())
        self.label_676.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_676.setFont(font)
        self.label_676.setObjectName("label_676")
        self.gridLayout_29.addWidget(self.label_676, 0, 4, 1, 1)
        self.lineEdit_437 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_437.sizePolicy().hasHeightForWidth())
        self.lineEdit_437.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_437.setFont(font)
        self.lineEdit_437.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_437.setObjectName("lineEdit_437")
        self.gridLayout_29.addWidget(self.lineEdit_437, 2, 5, 1, 1)
        self.lineEdit_370 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_370.sizePolicy().hasHeightForWidth())
        self.lineEdit_370.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_370.setFont(font)
        self.lineEdit_370.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_370.setObjectName("lineEdit_370")
        self.gridLayout_29.addWidget(self.lineEdit_370, 1, 3, 1, 1)
        self.lineEdit_367 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_367.sizePolicy().hasHeightForWidth())
        self.lineEdit_367.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_367.setFont(font)
        self.lineEdit_367.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_367.setObjectName("lineEdit_367")
        self.gridLayout_29.addWidget(self.lineEdit_367, 1, 0, 1, 1)
        self.lineEdit_432 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_432.sizePolicy().hasHeightForWidth())
        self.lineEdit_432.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_432.setFont(font)
        self.lineEdit_432.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_432.setObjectName("lineEdit_432")
        self.gridLayout_29.addWidget(self.lineEdit_432, 2, 0, 1, 1)
        self.lineEdit_373 = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_373.sizePolicy().hasHeightForWidth())
        self.lineEdit_373.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_373.setFont(font)
        self.lineEdit_373.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_373.setObjectName("lineEdit_373")
        self.gridLayout_29.addWidget(self.lineEdit_373, 1, 6, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(Form)
        self.pushButton_42.setGeometry(QtCore.QRect(240, 700, 111, 71))
        self.pushButton_42.setObjectName("pushButton_42")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 620, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(530, 620, 551, 271))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalSlider_47 = QtWidgets.QSlider(self.layoutWidget_4)
        self.verticalSlider_47.setMaximum(19)
        self.verticalSlider_47.setProperty("value", 15)
        self.verticalSlider_47.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_47.setObjectName("verticalSlider_47")
        self.horizontalLayout.addWidget(self.verticalSlider_47)
        self.verticalSlider_45 = QtWidgets.QSlider(self.layoutWidget_4)
        self.verticalSlider_45.setMinimum(-20)
        self.verticalSlider_45.setMaximum(25)
        self.verticalSlider_45.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_45.setObjectName("verticalSlider_45")
        self.horizontalLayout.addWidget(self.verticalSlider_45)
        self.verticalSlider_44 = QtWidgets.QSlider(self.layoutWidget_4)
        self.verticalSlider_44.setMaximum(80)
        self.verticalSlider_44.setSingleStep(1)
        self.verticalSlider_44.setPageStep(10)
        self.verticalSlider_44.setProperty("value", 30)
        self.verticalSlider_44.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_44.setObjectName("verticalSlider_44")
        self.horizontalLayout.addWidget(self.verticalSlider_44)
        self.verticalSlider_46 = QtWidgets.QSlider(self.layoutWidget_4)
        self.verticalSlider_46.setMaximum(12)
        self.verticalSlider_46.setProperty("value", 4)
        self.verticalSlider_46.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_46.setObjectName("verticalSlider_46")
        self.horizontalLayout.addWidget(self.verticalSlider_46)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(310, 509, 211, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.label_567 = QtWidgets.QLabel(Form)
        self.label_567.setGeometry(QtCore.QRect(581, 496, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_567.sizePolicy().hasHeightForWidth())
        self.label_567.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_567.setFont(font)
        self.label_567.setObjectName("label_567")
        self.label_607 = QtWidgets.QLabel(Form)
        self.label_607.setGeometry(QtCore.QRect(705, 531, 101, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_607.sizePolicy().hasHeightForWidth())
        self.label_607.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_607.setFont(font)
        self.label_607.setObjectName("label_607")
        self.label_566 = QtWidgets.QLabel(Form)
        self.label_566.setGeometry(QtCore.QRect(829, 506, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_566.sizePolicy().hasHeightForWidth())
        self.label_566.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_566.setFont(font)
        self.label_566.setObjectName("label_566")
        self.label_603 = QtWidgets.QLabel(Form)
        self.label_603.setGeometry(QtCore.QRect(950, 520, 181, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_603.sizePolicy().hasHeightForWidth())
        self.label_603.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_603.setFont(font)
        self.label_603.setObjectName("label_603")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_602.setText(_translate("Form", "出工作坑导向计算器"))
        self.pushButton_36.setText(_translate("Form", "机器暂停"))
        self.label_665.setText(_translate("Form", "剩下距离"))
        self.label_680.setText(_translate("Form", "度数误差范围"))
        self.lineEdit_375.setText(_translate("Form", "3"))
        self.lineEdit_376.setText(_translate("Form", "20"))
        self.label_664.setText(_translate("Form", "出坑要求高度"))
        self.lineEdit_359.setText(_translate("Form", "13"))
        self.label_682.setText(_translate("Form", "每杆最大角度"))
        self.lineEdit_362.setText(_translate("Form", "6"))
        self.lineEdit_360.setText(_translate("Form", "13"))
        self.label_663.setText(_translate("Form", "出坑要求角度"))
        self.lineEdit_361.setText(_translate("Form", "15"))
        self.label_681.setText(_translate("Form", "高度误差范围"))
        self.label_668.setText(_translate("Form", "当前深度"))
        self.label_666.setText(_translate("Form", "钻杆数"))
        self.lineEdit_377.setText(_translate("Form", "4"))
        self.lineEdit_364.setText(_translate("Form", "31"))
        self.lineEdit_365.setText(_translate("Form", "0"))
        self.label_669.setText(_translate("Form", "当前钻杆角"))
        self.label_674.setText(_translate("Form", "6杆度数"))
        self.label_673.setText(_translate("Form", "2杆度数"))
        self.label_672.setText(_translate("Form", "1杆度数"))
        self.label_677.setText(_translate("Form", "计划出高"))
        self.label_679.setText(_translate("Form", "计划出角"))
        self.label_671.setText(_translate("Form", "3杆度数"))
        self.label_675.setText(_translate("Form", "4杆度数"))
        self.label_676.setText(_translate("Form", "5杆度数"))
        self.pushButton_42.setText(_translate("Form", "计算"))
        self.radioButton_2.setText(_translate("Form", "高度优先"))
        self.radioButton.setText(_translate("Form", "角度优先"))
        self.label_567.setText(_translate("Form", "当前钻杆角度"))
        self.label_607.setText(_translate("Form", "剩下距离"))
        self.label_566.setText(_translate("Form", "当前深度"))
        self.label_603.setText(_translate("Form", "每杆最大角度"))
