# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 833)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(36, 19, 871, 731))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(350, 50, 321, 544))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton_14)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_23)
        self.pushButton_22 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pushButton_22)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineEdit_31)
        self.pushButton_15 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.pushButton_15)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.pushButton_16 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.pushButton_16)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEdit_27)
        self.pushButton_17 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.pushButton_17)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.pushButton_18 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.pushButton_18)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineEdit_25)
        self.pushButton_19 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.pushButton_19)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.pushButton_20 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.pushButton_20)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.lineEdit_26)
        self.pushButton_21 = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.pushButton_21)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.lineEdit_24)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton_5.setText(_translate("MainWindow", "钻杆公丝到达虎牙中间"))
        self.pushButton_6.setText(_translate("MainWindow", "退20丝位置"))
        self.pushButton_7.setText(_translate("MainWindow", "退到可以退丝的位置"))
        self.pushButton_8.setText(_translate("MainWindow", "退到距尾部5公分位置"))
        self.pushButton_9.setText(_translate("MainWindow", "到达可以接钻杆的位置"))
        self.pushButton_10.setText(_translate("MainWindow", "到达最后一根钻杆卸东西位置"))
        self.pushButton_11.setText(_translate("MainWindow", "钻箱下到可以抓手取杆位置"))
        self.pushButton_12.setText(_translate("MainWindow", "钻箱上到位"))
        self.pushButton_13.setText(_translate("MainWindow", "钻箱下到位"))
        self.pushButton_14.setText(_translate("MainWindow", "人工上钻杆位置"))
        self.pushButton_22.setText(_translate("MainWindow", "人工上钻杆退到位位置"))
        self.pushButton_15.setText(_translate("MainWindow", "人工下钻杆位置"))
        self.pushButton_16.setText(_translate("MainWindow", "钻杆箱1号位置"))
        self.pushButton_17.setText(_translate("MainWindow", "钻杆箱2号位置"))
        self.pushButton_18.setText(_translate("MainWindow", "钻杆箱3号位置"))
        self.pushButton_19.setText(_translate("MainWindow", "抓手到达大梁取杆位置"))
        self.pushButton_20.setText(_translate("MainWindow", "抓手到达大梁开抓手位置"))
        self.pushButton_21.setText(_translate("MainWindow", "抓手到达不影响大梁运行位置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
