# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '通信查询.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1160, 899)
        self.pushButton_txcx = QtWidgets.QPushButton(Form)
        self.pushButton_txcx.setGeometry(QtCore.QRect(40, 100, 101, 21))
        self.pushButton_txcx.setObjectName("pushButton_txcx")
        self.pushButton_txcx_2 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_2.setGeometry(QtCore.QRect(40, 150, 101, 21))
        self.pushButton_txcx_2.setObjectName("pushButton_txcx_2")
        self.pushButton_txcx_3 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_3.setGeometry(QtCore.QRect(40, 190, 101, 21))
        self.pushButton_txcx_3.setObjectName("pushButton_txcx_3")
        self.pushButton_txcx_4 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_4.setGeometry(QtCore.QRect(40, 230, 101, 21))
        self.pushButton_txcx_4.setObjectName("pushButton_txcx_4")
        self.pushButton_txcx_5 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_5.setGeometry(QtCore.QRect(40, 270, 101, 21))
        self.pushButton_txcx_5.setObjectName("pushButton_txcx_5")
        self.stackedWidget_txcx = QtWidgets.QStackedWidget(Form)
        self.stackedWidget_txcx.setGeometry(QtCore.QRect(170, 70, 921, 561))
        self.stackedWidget_txcx.setObjectName("stackedWidget_txcx")
        self.page_txcx = QtWidgets.QWidget()
        self.page_txcx.setObjectName("page_txcx")
        self.tableView = QtWidgets.QTableView(self.page_txcx)
        self.tableView.setGeometry(QtCore.QRect(40, 40, 861, 481))
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.stackedWidget_txcx.addWidget(self.page_txcx)
        self.page_txcx_2 = QtWidgets.QWidget()
        self.page_txcx_2.setObjectName("page_txcx_2")
        self.tableView_txcx_2 = QtWidgets.QTableView(self.page_txcx_2)
        self.tableView_txcx_2.setGeometry(QtCore.QRect(5, 50, 901, 481))
        self.tableView_txcx_2.setObjectName("tableView_txcx_2")
        self.stackedWidget_txcx.addWidget(self.page_txcx_2)
        self.page_txcx_3 = QtWidgets.QWidget()
        self.page_txcx_3.setObjectName("page_txcx_3")
        self.tableView_txcx_3 = QtWidgets.QTableView(self.page_txcx_3)
        self.tableView_txcx_3.setGeometry(QtCore.QRect(10, 30, 881, 441))
        self.tableView_txcx_3.setObjectName("tableView_txcx_3")
        self.stackedWidget_txcx.addWidget(self.page_txcx_3)
        self.pushButton_txcx_6 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_6.setGeometry(QtCore.QRect(40, 310, 101, 21))
        self.pushButton_txcx_6.setObjectName("pushButton_txcx_6")
        self.pushButton_txcx_7 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_7.setGeometry(QtCore.QRect(40, 350, 101, 21))
        self.pushButton_txcx_7.setObjectName("pushButton_txcx_7")
        self.pushButton_txcx_8 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_8.setGeometry(QtCore.QRect(40, 390, 101, 21))
        self.pushButton_txcx_8.setObjectName("pushButton_txcx_8")
        self.pushButton_txcx_9 = QtWidgets.QPushButton(Form)
        self.pushButton_txcx_9.setGeometry(QtCore.QRect(40, 430, 101, 21))
        self.pushButton_txcx_9.setObjectName("pushButton_txcx_9")

        self.retranslateUi(Form)
        self.stackedWidget_txcx.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_txcx.setText(_translate("Form", "086数据读取"))
        self.pushButton_txcx_2.setText(_translate("Form", "手机数据读取"))
        self.pushButton_txcx_3.setText(_translate("Form", "小号——》大号"))
        self.pushButton_txcx_4.setText(_translate("Form", "按周查询"))
        self.pushButton_txcx_5.setText(_translate("Form", "按月查询"))
        self.pushButton_txcx_6.setText(_translate("Form", "按号码查询"))
        self.pushButton_txcx_7.setText(_translate("Form", "按名字查询"))
        self.pushButton_txcx_8.setText(_translate("Form", "组合查询"))
        self.pushButton_txcx_9.setText(_translate("Form", "名单"))
